"""Full synthetic examples generated through the real backend; no market claims."""
import json
from pathlib import Path
import tempfile

from src.paper.live_session import LocalPaperSession
from test_local_paper_session import FakeSource, BASE, stream_bar
from datetime import timedelta


def examples(directory):
    source = FakeSource()
    session = LocalPaperSession(source=source, journal_dir=directory)
    session.start()
    session.on_connection(True, None)
    source.phase = 1
    source.now = int((BASE + timedelta(minutes=16)).timestamp() * 1000)
    for symbol in ('BTCUSDT', 'ETHUSDT', 'SOLUSDT'):
        session.on_stream_event(stream_bar(symbol))
    normal = session.state()
    session.on_connection(False, 'synthetic disconnect')
    disconnected = session.state()
    session.on_connection(True, None)
    session.status = 'QUARANTINED'
    session.error = 'synthetic funding provenance unavailable'
    blocked = session.state()
    restarted = LocalPaperSession(source=source, journal_dir=directory).state()
    (directory / 'account.json').write_text('{', encoding='utf-8')
    corrupted = LocalPaperSession(source=source, journal_dir=directory).state()
    return {'normal': normal, 'disconnected': disconnected, 'blocked_data': blocked,
            'after_restart': restarted, 'unknown_account': corrupted}


def test_full_api_examples_match_schema_and_recovery_semantics(tmp_path):
    from jsonschema import Draft202012Validator, FormatChecker
    root = Path(__file__).resolve().parents[1]
    schema = json.loads((root / 'docs/operations/paper_stream_state.schema.json').read_text())
    validator = Draft202012Validator(schema, format_checker=FormatChecker())
    for state in examples(tmp_path).values():
        validator.validate(state)
        if state['status'] != 'SCANNING':
            assert state['risk_gate']['admission_open'] is False
    stored = json.loads((root / 'docs/operations/paper_stream_api_examples.json').read_text())
    for name, state in stored.items():
        if name != '_note':
            validator.validate(state)


if __name__ == '__main__':
    with tempfile.TemporaryDirectory() as directory:
        result = examples(Path(directory))
    result['_note'] = 'Full synthetic fixtures generated by tests/test_paper_api_examples.py. Not public market or performance evidence.'
    target = Path(__file__).resolve().parents[1] / 'docs/operations/paper_stream_api_examples.json'
    target.write_text(json.dumps(result, indent=2) + '\n', encoding='utf-8')
